# @format

name: phone_otp_ui
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.17.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  pinput: ^2.2.12
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.4
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  modal_progress_hud_nsn: ^0.3.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  pdf: ^3.1.0
  path_provider: ^2.0.1
  intl: ^0.17.0
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  http: ^0.13.5
  url_launcher: ^6.1.7
  open_file: ^3.2.1
  list_wheel_scroll_view_nls: ^0.0.3
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  splashscreen: ^1.3.5
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.1.1

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/LatestIcon.png'
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: IslandMoments
      fonts:
        - asset: fonts/ShadowsIntoLight-Regular.ttf
